### ISSUE TITLE
Wrong example of 'NotInTTS' property given

### ISSUE THREAD

**Issue by samee-r** [MicrosoftDocs/DynamicsAX2012-msdn#42]
'CustTable' doesn't have 'NotInTTS' property. Instead, it has 'Found' property. 

Please correct it as bloggers all over the internet are showing same copy pasted information on their blogs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9d38651-b818-9cd5-596b-77320993ba48
* Version Independent ID: fdfce311-6e2f-6f30-2a74-d41df70eac92
* Content: [Single-record Caching](https://docs.microsoft.com/en-us/dynamicsax-2012/developer/single-record-caching#feedback)
* Content Source: [dynamicsax2012-msdn/single-record-caching.md](https://github.com/microsoftdocs/DynamicsAX2012-msdn/blob/live/dynamicsax2012-msdn/single-record-caching.md)
* Product: **dynamics-ax-2012**
* GitHub Login: @Khairunj

**Comment by samee-r** [comment]
Hi @RobinARH 

The webpage has not been corrected with the right information yet & it will cause spread of misinformation among developers.
Then why the issue has been closed?

**Comment by RobinARH** [comment]
This content is archived and we are no longer updating it.
