### ISSUE TITLE
Naming standard for parameters and local private variable seems flipped

### ISSUE THREAD

**Issue by ThatRickGuy** [MicrosoftDocs/DynamicsAX2012-msdn#74]
Am I reading this correctly that the naming standard for formal parameters and local private variables is the opposite from that of C#? 

In C#, my local private variable would be "_identifier" and the constructor's formal parameter would be camel cased without the prefix as "identifier"

But this article suggests that the formal parameter should be "_identifier" and the local private variable would be "identifier"

Is this still the standard in 365? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f6fa39a-9574-328d-bb07-ad16218c7de9
* Version Independent ID: 31a975b9-185d-9b85-5ce4-0479fbfa2b58
* Content: [Naming Conventions: Underscores](https://docs.microsoft.com/en-us/dynamicsax-2012/developer/naming-conventions-underscores)
* Content Source: [dynamicsax2012-msdn/naming-conventions-underscores.md](https://github.com/microsoftdocs/DynamicsAX2012-msdn/blob/live/dynamicsax2012-msdn/naming-conventions-underscores.md)
* Product: **dynamics-ax-2012**
* GitHub Login: @Khairunj

**Comment by RobinARH** [comment]
We are not updating this content, and we did not bring this content forward into Dynamics AX or the Finance and Operations apps.
